namespace Confuser.Protections.Compress {
	/// <summary>
	///     Curated moduli for the compressor key-derivation generator (state = state * state % m).
	///     One value from each set is chosen per pack and injected into both the obfuscator-side
	///     <see cref="CompressorContext.Encrypt" /> and the runtime Decrypt method (via mutation
	///     keys), replacing the historic fixed constants that let de4dot/AV fingerprint the stub.
	///
	///     The round-trip is correct for any modulus (encrypt and decrypt share it), so these are
	///     selected purely to preserve key-stream quality: each is prime and congruent to 3 mod 4
	///     (so squaring permutes the quadratic residues and the stream cannot collapse), matches the
	///     bit-length of the original constant, and was validated to mix at least as well as it.
	///     Generated by scripts/curate_primes.py (seed 69).
	/// </summary>
	internal static class CompressorPrimes {
		// state advance -> src[i]   (was 0x143fc089, 29-bit)
		internal static readonly uint[] State = {
			0x11d61057, 0x11f35013, 0x120a8c8f, 0x1215d013, 0x12218207, 0x125bf20b, 0x125e2b3b, 0x1290f8cb,
			0x12980867, 0x12aa3107, 0x12cf99af, 0x12e6d2b7, 0x12f71a9b, 0x13048633, 0x13494d0f, 0x134f4aaf,
			0x135e2afb, 0x13903b77, 0x13a49a63, 0x13df88cb, 0x144c881f, 0x147c68e7, 0x1530e5f3, 0x153e189f,
			0x156e4fb3, 0x15a22ab3, 0x15c89ad3, 0x15dc05eb, 0x1622512f, 0x1657087f, 0x165d0cd3, 0x169cc6f3
		};

		// key-word derivation -> dst[i]   (was 0x444d56fb, 31-bit)
		internal static readonly uint[] KeyWord = {
			0x4049d5b7, 0x40ba619f, 0x413406a3, 0x4193e83b, 0x42668e5b, 0x427747c3, 0x43e4871f, 0x43e4f6eb,
			0x43ee3c57, 0x44591adf, 0x446a5873, 0x44e756df, 0x4502f48b, 0x4528b713, 0x45422afb, 0x45630b9b,
			0x45efbb6b, 0x4743e4eb, 0x476bf247, 0x47d6f76f, 0x48bb09db, 0x48be1ce7, 0x494d9b8f, 0x49cd1e3f,
			0x4a07494f, 0x4a169e4b, 0x4a18a703, 0x4a76dba3, 0x4ae9ea1b, 0x4aedf543, 0x4b3edb83, 0x4bc34bd3
		};

		// data-stream advance   (was 0x8a5cb7, 24-bit)
		internal static readonly uint[] Stream = {
			0x00807263, 0x00812957, 0x008226fb, 0x00837437, 0x0084506b, 0x0085d83f, 0x00866623, 0x0086cf7b,
			0x0088824b, 0x008903e7, 0x008a8c33, 0x008b20a7, 0x008b409b, 0x008b7b0f, 0x008bddef, 0x008de30f,
			0x008eabc3, 0x008ed3db, 0x00901ba7, 0x00908497, 0x0090a2e3, 0x0090df37, 0x0090e6a7, 0x0091306f,
			0x0091922f, 0x00925733, 0x00938e2b, 0x0093aaff, 0x00940987, 0x009825b3, 0x0099edb3, 0x009a9ac3
		};
	}
}
