#!/usr/bin/env python3
"""Curate full-period xorshift32 triples for the Constants protection key generator.

Constant.Initialize (runtime) and EncodePhase (obfuscator) both seed a 32-bit xorshift
of the exact form

    n ^= n >> a;  n ^= n << b;  n ^= n >> c;

to expand a seed into the key stream. Both sides must use the same (a, b, c); the historic
fixed 12/25/27 fingerprints the stub. A replacement triple is only valid if the generator
still has full period 2**32 - 1 (otherwise the key stream degenerates).

The step map is linear over GF(2), so the whole round is a 32x32 bit matrix M. The period
is the multiplicative order of M and equals 2**32 - 1 iff

    M**(2**32-1) == I   and   M**((2**32-1)/p) != I  for every prime p | (2**32-1).

2**32-1 = 3 * 5 * 17 * 257 * 65537. This is the standard primitivity test and is exact.
Emits Confuser.Protections/Constants/ConstantXorshift.cs. Deterministic; run from repo root:
    python scripts/curate_xorshift.py
"""
import math
import os

MASK = 0xFFFFFFFF
N = 32
PERIOD = (1 << 32) - 1
FACTORS = (3, 5, 17, 257, 65537)
IDENT = [1 << j for j in range(N)]
OUT = os.path.join(os.path.dirname(__file__), "..", "Confuser.Protections", "Constants", "ConstantXorshift.cs")


def step(n, a, b, c):
    n &= MASK
    n ^= n >> a
    n ^= (n << b) & MASK
    n ^= n >> c
    return n & MASK


def apply(M, v):                       # matrix (columns) times bit-vector, over GF(2)
    r = j = 0
    while v:
        if v & 1:
            r ^= M[j]
        v >>= 1
        j += 1
    return r & MASK


def matmul(A, B):                      # apply B then A
    return [apply(A, B[j]) for j in range(N)]


def matpow(M, e):
    r = IDENT
    while e:
        if e & 1:
            r = matmul(r, M)
        M = matmul(M, M)
        e >>= 1
    return r


def full_period(a, b, c):
    M = [step(1 << j, a, b, c) for j in range(N)]   # column j = image of basis vector e_j
    if matpow(M, PERIOD) != IDENT:
        return False
    return all(matpow(M, PERIOD // p) != IDENT for p in FACTORS)


def fmt(triples):
    rows = []
    for i in range(0, len(triples), 4):
        rows.append("\t\t\t" + " ".join(f"new byte[] {{ {a}, {b}, {c} }}," for a, b, c in triples[i:i + 4]))
    return "\n".join(rows).rstrip(",")


def main():
    # non-extreme shifts (2..30) give better avalanche over the 16-word expansion
    good = [(a, b, c)
            for a in range(2, N - 1) for b in range(2, N - 1) for c in range(2, N - 1)
            if full_period(a, b, c)]
    print(f"original 12/25/27 full-period: {full_period(12, 25, 27)}")
    print(f"curated full-period (>>a,<<b,>>c) triples, shifts 2..30: {len(good)} "
          f"({math.log2(len(good)):.1f} bits)")

    cs = f"""namespace Confuser.Protections.Constants {{
\t/// <summary>
\t///     Curated full-period xorshift32 triples (a, b, c) for the constant key generator
\t///     n ^= n >> a; n ^= n << b; n ^= n >> c. One triple is chosen per module and injected
\t///     into the runtime Constant.Initialize (Mutation.KeyI2/KeyI3/KeyI4), replacing the fixed
\t///     12/25/27 that de4dot/AV pattern-match. Both the obfuscator and the runtime use the same
\t///     triple, so the round-trip holds for any shifts; each listed triple is additionally a
\t///     full-period generator (period 2^32-1, verified by GF(2) matrix order) with non-extreme
\t///     shifts, so the expanded key stream is well mixed -- unlike the historic 12/25/27, which
\t///     is not full period. Generated by scripts/curate_xorshift.py.
\t/// </summary>
\tinternal static class ConstantXorshift {{
\t\tinternal static readonly byte[][] Triples = {{
{fmt(good)}
\t\t}};
\t}}
}}
"""
    with open(OUT, "w", newline="\n") as fh:
        fh.write(cs)
    print(f"wrote {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
