#!/usr/bin/env python3
"""Curate the compressor key-derivation moduli baked into CompressorPrimes.cs.

The compressor derives its key stream with  state = state * state % m  on both the
obfuscator side (CompressorContext.Encrypt) and the injected runtime (Decrypt). The
round-trip is correct for ANY modulus because both sides share it, so the historic
fixed constants (0x143fc089 / 0x444d56fb / 0x8a5cb7 — which are not even prime) can be
replaced per pack to kill the de4dot/AV fingerprint. This script selects the curated
replacement sets, choosing values that preserve key-stream quality:

  * prime and congruent to 3 mod 4  -> squaring permutes the quadratic residues, so the
    stream cannot collapse to a fixed point for residue seeds;
  * same bit-length as the original -> preserves value ranges (no (uint) truncation);
  * mixing health at least as good as the original, measured by simulating the exact
    ulong generator over thousands of random 32-bit seeds.

Deterministic (seed 69) so the emitted set is reproducible. Run from the repo root:
    python scripts/curate_primes.py
"""
import math
import os
import random

random.seed(69)
MASK64 = (1 << 64) - 1
ORIG = {"State": 0x143fc089, "KeyWord": 0x444d56fb, "Stream": 0x8a5cb7}
COUNT = 32
OUT = os.path.join(os.path.dirname(__file__), "..", "Confuser.Protections", "Compress", "CompressorPrimes.cs")


def is_prime(n):
    if n < 2:
        return False
    for p in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37):
        if n % p == 0:
            return n == p
    d, r = n - 1, 0
    while d % 2 == 0:
        d //= 2
        r += 1
    for a in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37):  # deterministic for n < 3.3e24
        x = pow(a, d, n)
        if x in (1, n - 1):
            continue
        for _ in range(r - 1):
            x = x * x % n
            if x == n - 1:
                break
        else:
            return False
    return True


def health(m, seeds=4000, iters=64):
    """Return (collapse_count, min_distinct_ratio) for state = state*state % m over ulong."""
    collapse, worst = 0, 1.0
    for _ in range(seeds):
        s, seen, stalled = random.getrandbits(32), set(), False
        for _ in range(iters):
            s = ((s * s) & MASK64) % m
            if s in (0, 1):
                stalled = True
                break
            seen.add(s)
        collapse += stalled
        worst = min(worst, len(seen) / iters)
    return collapse, worst


def curate(orig, min_w, band=0.12):
    lo = max(int(orig * (1 - band)), 1 << (orig.bit_length() - 1))
    hi = min(int(orig * (1 + band)), (1 << orig.bit_length()) - 1)
    seen, out = set(), []
    while len(out) < COUNT:
        n = (random.randrange(lo, hi) & ~3) | 3          # odd, == 3 mod 4
        if n in seen or n.bit_length() != orig.bit_length():
            continue
        seen.add(n)
        if not is_prime(n):
            continue
        c, w = health(n, seeds=1500)
        if c == 0 and w >= min_w:
            out.append(n)
    return sorted(out)


def fmt(arr):
    rows = ["\t\t\t" + ", ".join(f"0x{p:08x}" for p in arr[i:i + 8]) + "," for i in range(0, len(arr), 8)]
    return "\n".join(rows).rstrip(",")


def main():
    cur, bars = {}, {}
    for name, v in ORIG.items():
        _, w = health(v)
        bars[name] = min(w * 0.98, 0.95)
        cur[name] = curate(v, bars[name])
        print(f"{name}: original 0x{v:08x} prime={is_prime(v)} bitlen={v.bit_length()} "
              f"minDistinct={w:.3f} -> {len(cur[name])} curated primes (bar>={bars[name]:.3f})")
    bits = math.log2(len(cur["State"]) * len(cur["KeyWord"]) * len(cur["Stream"]))
    print(f"per-pack identity contribution: {bits:.1f} bits")

    cs = f"""namespace Confuser.Protections.Compress {{
	/// <summary>
	///     Curated moduli for the compressor key-derivation generator (state = state * state % m).
	///     One value from each set is chosen per pack and injected into both the obfuscator-side
	///     <see cref="CompressorContext.Encrypt" /> and the runtime Decrypt method (via mutation
	///     keys), replacing the historic fixed constants that let de4dot/AV fingerprint the stub.
	///
	///     The round-trip is correct for any modulus (encrypt and decrypt share it), so these are
	///     selected purely to preserve key-stream quality: each is prime and congruent to 3 mod 4
	///     (so squaring permutes the quadratic residues and the stream cannot collapse), matches the
	///     bit-length of the original constant, and was validated to mix at least as well as it.
	///     Generated by scripts/curate_primes.py (seed 69).
	/// </summary>
	internal static class CompressorPrimes {{
		// state advance -> src[i]   (was 0x143fc089, 29-bit)
		internal static readonly uint[] State = {{
{fmt(cur['State'])}
		}};

		// key-word derivation -> dst[i]   (was 0x444d56fb, 31-bit)
		internal static readonly uint[] KeyWord = {{
{fmt(cur['KeyWord'])}
		}};

		// data-stream advance   (was 0x8a5cb7, 24-bit)
		internal static readonly uint[] Stream = {{
{fmt(cur['Stream'])}
		}};
	}}
}}
"""
    with open(OUT, "w", newline="\n") as fh:
        fh.write(cs)
    print(f"wrote {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
